name: Swagger Diff

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      old_spec_url:
        description: 'URL for old Swagger specification'
        required: true
      new_spec_url:
        description: 'URL for new Swagger specification'
        required: true

jobs:
  compare-swagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install openapi-diff
        run: npm install -g @openapitools/openapi-diff

      - name: Download old Swagger specification
        run: curl -o old-spec.yaml ${{ github.event.inputs.old_spec_url }}

      - name: Download new Swagger specification
        run: curl -o new-spec.yaml ${{ github.event.inputs.new_spec_url }}

      - name: Compare Swagger files
        id: diff
        run: |
          openapi-diff old-spec.yaml new-spec.yaml --fail-on-incompatible > diff.txt
          cat diff.txt

      - name: Save diff as artifact
        if: always()
        uses: actions/upload-artifact@v2.2.3
        with:
          name: swagger-diff
          path: diff.txt
