name: Swagger Diff

on:
  workflow_dispatch:
    inputs:
      old_spec_url:
        description: 'URL для старой спецификации (JSON/YAML)'
        required: true
      new_spec_url:
        description: 'URL для новой спецификации (JSON/YAML)'
        required: true

jobs:
  compare-swagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download old Swagger specification
        run: |
          echo "Downloading old spec from ${{ github.event.inputs.old_spec_url }}"
          curl -sS -o old-spec.json "${{ github.event.inputs.old_spec_url }}"
          # Для отладки (необязательно):
          echo "=== OLD SPEC HEAD ==="
          head -n 10 old-spec.json

      - name: Download new Swagger specification
        run: |
          echo "Downloading new spec from ${{ github.event.inputs.new_spec_url }}"
          curl -sS -o new-spec.json "${{ github.event.inputs.new_spec_url }}"
          # Для отладки (необязательно):
          echo "=== NEW SPEC HEAD ==="
          head -n 10 new-spec.json

      - name: Compare Swagger files via Docker
        id: diff
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/specs \
            openapitools/openapi-diff:latest \
            /specs/old-spec.json /specs/new-spec.json --fail-on-incompatible > diff.txt
          echo "=== DIFF OUTPUT ==="
          cat diff.txt

      - name: Upload diff as artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: swagger-diff
          path: diff.txt
