name: Swagger Diff

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      old_spec_url:
        description: 'URL для старой спецификации Swagger'
        required: true
      new_spec_url:
        description: 'URL для новой спецификации Swagger'
        required: true

jobs:
  compare-swagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install openapi-diff
        run: npm install -g @openapitools/openapi-diff

      - name: Download old Swagger specification
        run: curl -sS -o old-spec.yaml ${{ github.event.inputs.old_spec_url }}

      - name: Download new Swagger specification
        run: curl -sS -o new-spec.yaml ${{ github.event.inputs.new_spec_url }}

      - name: Compare Swagger files
        id: diff
        run: |
          openapi-diff old-spec.yaml new-spec.yaml --fail-on-incompatible > diff.txt
          cat diff.txt

      - name: Upload diff as artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: swagger-diff
          path: diff.txt
